plugins:
  install:
    - grafana-image-renderer

securityContext:
  runAsUser: 0
  fsGroup: 1000

extraVolumes:
  - name: plugins
    emptyDir: {}

extraVolumeMounts:
  - name: plugins
    mountPath: /opt/bitnami/grafana/data/plugins
    subPath: plugins
    readOnly: false
